### ISSUE TITLE
Elevenlabs config

### ISSUE THREAD

**Issue by solo2424** [leopiney/neuralnoise#4]
Can someone help me with the command to run the elevenlabs config instead of the openai?

**Comment by leopiney** [comment]
Hey there! There's a configuration example in the config folder

https://github.com/leopiney/neuralnoise/blob/main/config/config_elevenlabs.json

If you go to the voices section in  ElevenLabs you'll see the voices and if you select them you can get the voice id. This works even with your custom voices. 

Let me know how it works!

Thanks
